theme: jekyll-theme-slate
title: "HALO"
description: "HALO: A Skeleton-Driven Neural Occupancy Representation for Articulated Hands"

defaults:
  - scope:
      path: "assets"
    values:
      image: true
