theme: jekyll-theme-slate
title: "HALO"
description: "HALO: A Skeleton-Driven Neural Occupancy Representation for Articulated Hands"

defaults:
  - scope:
      path: "assets"
    values:
      image: true


{% assign image_files = site.static_files | where: "image", true %}
{% for myimage in image_files %}
  {{ myimage.path }}
{% endfor %}
